apiVersion: v1
kind: ServiceAccount
metadata:
  name: azuredevopscd
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: azuredevopsrole
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azuredevopsrolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: azuredevopsrole
subjects:
- namespace: default
  kind: ServiceAccount
  name: azuredevopscd